name: CI
on:
  workflow_run:
    workflows: ["Draft release"]
    types:
      - completed
jobs:
  # TODO(build-system): enable x86 Linux CI here, dependency cycle in build.zig
  # x86_64-linux:
  #   if: ${{ !contains(github.event.head_commit.message, 'update to latest binary release') }}
  #   runs-on: ubuntu-latest
  #   # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push
  #   # to the branch.
  #   if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Zig
  #       run: |
  #         sudo apt install xz-utils
  #         sudo sh -c 'wget -c https://ziglang.org/builds/zig-linux-x86_64-0.10.0-dev.670+e1a535360.tar.xz -O - | tar -xJ --strip-components=1 -C /usr/local/bin'
  #     - name: Clone mach-glfw
  #       run: rm libs/mach-glfw && git clone https://github.com/hexops/mach-glfw libs/mach-glfw
  #     - name: install (debug)
  #       run: zig build install -Dfrom-source=true
  #     - name: upload (debug)
  #       run: |
  #         mv zig-out/lib/libdawn.a zig-out/lib/libdawn_linux-x86_64_debug.a
  #         gzip -9 zig-out/lib/libdawn_linux-x86_64_debug.a
  #         gh release upload "release-$(git rev-parse --short HEAD)" zig-out/lib/libdawn_linux-x86_64_debug.a.gz
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     - name: install (release-fast)
  #       run: zig build install -Dfrom-source=true -Drelease-fast=true
  #     - name: upload (release-fast)
  #       run: |
  #         mv zig-out/lib/libdawn.a zig-out/lib/libdawn_linux-x86_64_release-fast.a
  #         gzip -9 zig-out/lib/libdawn_linux-x86_64_release-fast.a
  #         gh release upload "release-$(git rev-parse --short HEAD)" zig-out/lib/libdawn_linux-x86_64_release-fast.a.gz
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # TODO(build-system): enable windows CI here once gpu-dawn builds under Windows
  # x86_64-windows:
  #   if: ${{ !contains(github.event.head_commit.message, 'update to latest binary release') }}
  #   runs-on: windows-latest
  #   # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push
  #   # to the branch.
  #   if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Install Git
  #       run: choco install git
  #     - name: Setup Zig
  #       run: |
  #         Invoke-WebRequest -Uri "https://ziglang.org/builds/zig-windows-x86_64-0.10.0-dev.670+e1a535360.zip" -OutFile "C:\zig.zip"
  #         cd C:\
  #         7z x zig.zip
  #         Add-Content $env:GITHUB_PATH "C:\zig-windows-x86_64-0.10.0-dev.670+e1a535360\"
  #     - name: install (debug)
  #       run: zig build install -Dfrom-source=true
  #     # TODO: upload step for Windows
  x86_64-macos:
    if: ${{ !contains(github.event.head_commit.message, 'update to latest binary release') }}
    runs-on: macos-latest
    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push
    # to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Zig
        run: |
          brew install xz
          sudo sh -c 'wget -c https://ziglang.org/builds/zig-macos-x86_64-0.10.0-dev.670+e1a535360.tar.xz -O - | tar -xJ --strip-components=1 -C /usr/local/bin'
      - name: Clone mach-glfw
        run: rm libs/mach-glfw && git clone https://github.com/hexops/mach-glfw libs/mach-glfw
      - name: install (debug)
        run: zig build install -Dfrom-source=true
        env:
          AGREE: true
      - name: upload (debug)
        run: |
          mv zig-out/lib/libdawn.a zig-out/lib/libdawn_macos-x86_64_debug.a
          gzip -9 zig-out/lib/libdawn_macos-x86_64_debug.a
          gh release upload "release-$(git rev-parse --short HEAD)" zig-out/lib/libdawn_macos-x86_64_debug.a.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: install (release-fast)
        run: zig build install -Dfrom-source=true -Drelease-fast=true
        env:
          AGREE: true
      - name: upload (release-fast)
        run: |
          mv zig-out/lib/libdawn.a zig-out/lib/libdawn_macos-x86_64_release-fast.a
          gzip -9 zig-out/lib/libdawn_macos-x86_64_release-fast.a
          gh release upload "release-$(git rev-parse --short HEAD)" zig-out/lib/libdawn_macos-x86_64_release-fast.a.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
